"""Initial migration

Revision ID: d1240247ef43
Revises: 
Create Date: 2026-05-22 14:27:48.268337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1240247ef43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=20), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('cfg_scale', sa.Float(), nullable=True),
    sa.Column('sampler', sa.String(length=100), nullable=True),
    sa.Column('scheduler', sa.String(length=100), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_filename', sa.String(length=512), nullable=True),
    sa.Column('output_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_celery_task_id'), 'generation_jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_generation_jobs_user_id'), 'generation_jobs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documentary_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('voice', sa.String(length=100), nullable=True),
    sa.Column('music_style', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_url', sa.String(length=1024), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_tags', sa.Text(), nullable=True),
    sa.Column('chapters', sa.Text(), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=True),
    sa.Column('is_trailer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentary_projects_owner_id'), 'documentary_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documentary_projects_status'), 'documentary_projects', ['status'], unique=False)
    op.create_index(op.f('ix_documentary_projects_team_id'), 'documentary_projects', ['team_id'], unique=False)
    op.create_table('documentary_scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('image_job_id', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('video_job_id', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('subtitle_url', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['documentary_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentary_scenes_project_id'), 'documentary_scenes', ['project_id'], unique=False)
    op.create_index(op.f('ix_documentary_scenes_status'), 'documentary_scenes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentary_scenes_status'), table_name='documentary_scenes')
    op.drop_index(op.f('ix_documentary_scenes_project_id'), table_name='documentary_scenes')
    op.drop_table('documentary_scenes')
    op.drop_index(op.f('ix_documentary_projects_team_id'), table_name='documentary_projects')
    op.drop_index(op.f('ix_documentary_projects_status'), table_name='documentary_projects')
    op.drop_index(op.f('ix_documentary_projects_owner_id'), table_name='documentary_projects')
    op.drop_table('documentary_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_generation_jobs_user_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_celery_task_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
